### ISSUE TITLE
How did you annotate the videos?

### ISSUE THREAD

**Issue by yiminglin-ai** [ilchemla/gygo-dataset#4]
Hi Visualead,

Thanks for providing such a valuable dataset for the community. I am wondering how you annotated the dataset and if there is an open source tool available?  I am asking because I know per-pixel annotations are a lot of work and do not know how you managed it. I tried to find the answer in the DAVIS paper but no luck. 
Thank you.
Best regards,
Yiming

**Comment by eddiesmo** [comment]
Hi @yl1991 , 
Thank you for your interest, and sorry for the late response.
We annotated the dataset semi-automatically with a combination of Amazon Mechanical Turk and internal tools to automatically pre-process, post-process and combine the AMT annotations, which are not publicly available. 
I can't speak for the DAVIS dataset team but my understanding is that it was annotated by an external company which aimed for a very high precision and did it (mostly?) manually.
