### ISSUE TITLE
Baseline results

### ISSUE THREAD

**Issue by patrickpoirson** [ilchemla/gygo-dataset#5]
Hi,
Thanks for releasing your dataset. Do you guys have any baseline (e.g. OSVOS or MaskTrack)  numbers that I could compare to? If I were to use this in a paper how should I cite the dataset?

**Comment by eddiesmo** [comment]
Hi Patrick, thank you for the interest!
I've updated the Readme with a bibtex section and a benchmarks section. These should answer both of your questions.
